-- -- +goose Up
-- CREATE TABLE ideas (
--   id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
--   title VARCHAR(255),
--   body TEXT,
--   ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   utime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   user_id INT NOT NULL,
--   PRIMARY KEY (id),
--   FOREIGN KEY(user_id) REFERENCES users(id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
-- -- +goose Down
-- DROP TABLE ideas;
-- +goose Up
CREATE TABLE ideas (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255),
  body TEXT,
  user_id INT UNSIGNED NOT NULL,
  ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  utime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- +goose Down
DROP TABLE article;
